export const typeColors: Record<string, string> = {
  normal: "bg-[#b7b7aa]",
  fighting: "bg-[#d3887e]",
  flying: "bg-gradient-to-b from-[#3dc7ef] to-[#bdb9b8]",
  poison: "bg-[#c68bb7]",
  ground: "bg-gradient-to-b from-[#f7de3f] to-[#ab9842]",
  rock: "bg-[#baaa66]",
  bug: "bg-[#aabb23]",
  ghost: "bg-[#9995d0]",
  steel: "bg-[#abaabb]",
  fire: "bg-[#ff6f52]",
  water: "bg-[#42a1ff]",
  grass: "bg-[#78cc55]",
  electric: "bg-[#fecc33]",
  psychic: "bg-[#ff66a3]",
  ice: "bg-[#66ccfe]",
  dragon: "bg-gradient-to-b from-[#53a4cf] to-[#f16e57]",
  dark: "bg-[#b59682]",
  fairy: "bg-[#ed99ed]",
  stellar: "bg-gradient-rainbow",
};
